import Actividad from "./Actividad";
import Anadir from "./Anadir";
import Apple from "./Apple";
import Aprobado from "./Aprobado";
import Borrar from "./Borrar";
import Burbuja from "./Burbuja";
import Buscar from "./Buscar";
import Calendario from "./Calendario";
import Carro from "./Carro";
import Categoria from "./Categoria";
import Cerrar from "./Cerrar";
import CerrarPequeno from "./CerrarPequeno";
import Circulo from "./Circulo";
import CirculoAgregar from "./CirculoAgregar";
import CirculoAprobado from "./CirculoAprobado";
import CirculoDenegado from "./CirculoDenegado";
import CirculoQuitar from "./CirculoQuitar";
import Correo from "./Correo";
import Descuento from "./Descuento";
import Despejar from "./Despejar";
import Dinero from "./Dinero";
import Editar from "./Editar";
import Enlace from "./Enlace";
import Estrella from "./Estrella";
import Evento from "./Evento";
import Explorar from "./Explorar";
import Facebook from "./Facebook";
import Favorito from "./Favorito";
import FlechaAbajo from "./FlechaAbajo";
import FlechaArriba from "./FlechaArriba";
import FlechaDerecha from "./FlechaDerecha";
import FlechaIzquierda from "./FlechaIzquierda";
import Foro from "./Foro";
import Google from "./Google";
import Historial from "./Historial";
import Imagen from "./Imagen";
import Insatisfecho from "./Insatisfecho";
import Limite from "./Limite";
import Lista from "./Lista";
import Mapa from "./Mapa";
import Mercado from "./Mercado";
import Mezcla from "./Mezcla";
import Persona from "./Persona";
import Rebaja from "./Rebaja";
import Repetir from "./Repetir";
import Satisfecho from "./Satisfecho";
import Soporte from "./Soporte";
import Sustraer from "./Sustraer";
import Telefono from "./Telefono";
import Todo from "./Todo";
import Ubicacion from "./Ubicacion";
import Vender from "./Vender";
import Visibilidad from "./Visibilidad";
import VisibilidadDesactivada from "./VisibilidadDesactivada";
import Voluntariado from "./Voluntariado";
import Webpay from "./Webpay";

export { Actividad, Anadir, Apple, Aprobado, Borrar, Burbuja, Buscar, Calendario, Carro, Categoria, Cerrar, CerrarPequeno, Circulo, CirculoAgregar, CirculoAprobado, CirculoDenegado, CirculoQuitar, Correo, Descuento, Despejar, Dinero, Editar, Enlace, Estrella, Evento, Explorar, Facebook, Favorito, FlechaAbajo, FlechaArriba, FlechaDerecha, FlechaIzquierda, Foro, Google, Historial, Imagen, Insatisfecho, Limite, Lista, Mapa, Mercado, Mezcla, Persona, Rebaja, Repetir, Satisfecho, Soporte, Sustraer, Telefono, Todo, Ubicacion, Vender, Visibilidad, VisibilidadDesactivada, Voluntariado, Webpay, };

const Iconos = { Actividad, Anadir, Apple, Aprobado, Borrar, Burbuja, Buscar, Calendario, Carro, Categoria, Cerrar, CerrarPequeno, Circulo, CirculoAgregar, CirculoAprobado, CirculoDenegado, CirculoQuitar, Correo, Descuento, Despejar, Dinero, Editar, Enlace, Estrella, Evento, Explorar, Facebook, Favorito, FlechaAbajo, FlechaArriba, FlechaDerecha, FlechaIzquierda, Foro, Google, Historial, Imagen, Insatisfecho, Limite, Lista, Mapa, Mercado, Mezcla, Persona, Rebaja, Repetir, Satisfecho, Soporte, Sustraer, Telefono, Todo, Ubicacion, Vender, Visibilidad, VisibilidadDesactivada, Voluntariado, Webpay, };

export default Iconos;