import AccionCuaternaria from "./AccionCuaternaria";
import AccionPrimaria from "./AccionPrimaria";
import AccionQuinaria from "./AccionQuinaria";
import AccionSecundaria from "./AccionSecundaria";
import AccionTerciaria from "./AccionTerciaria";
import BotonCuaternario from "./BotonCuaternario";
import BotonPrimario from "./BotonPrimario";
import BotonSecundario from "./BotonSecundario";
import BotonTerciario from "./BotonTerciario";
import EnlaceAlternativoPrimario from "./EnlaceAlternativoPrimario";
import EnlaceAlternativoSecundario from "./EnlaceAlternativoSecundario";
import EnlaceCuaternario from "./EnlaceCuaternario";
import EnlacePrimario from "./EnlacePrimario";
import EnlaceSecundario from "./EnlaceSecundario";
import EnlaceTerciario from "./EnlaceTerciario";
import EntradaCampo from "./EntradaCampo";
import EntradaNumero from "./EntradaNumero";
import EntradaRadioPrimaria from "./EntradaRadioPrimaria";
import EntradaRadioSecundaria from "./EntradaRadioSecundaria";
import EntradaSeleccion from "./EntradaSeleccion";
import EntradaTexto from "./EntradaTexto";
import EntradaVerificacionPrimaria from "./EntradaVerificacionPrimaria";
import EntradaVerificacionSecundaria from "./EntradaVerificacionSecundaria";
import EtiquetaPrimaria from "./EtiquetaPrimaria";
import EtiquetaSecundaria from "./EtiquetaSecundaria";
import EtiquetaTerciaria from "./EtiquetaTerciaria";
import ListaPrimaria from "./ListaPrimaria";
import ParrafoCuaternario from "./ParrafoCuaternario";
import ParrafoPrimario from "./ParrafoPrimario";
import ParrafoSecundario from "./ParrafoSecundario";
import ParrafoTerciario from "./ParrafoTerciario";
import TituloPrimario from "./TituloPrimario";
import TituloSecundario from "./TituloSecundario";
import TituloTerciario from "./TituloTerciario";
import TituloCuaternario from "./TituloCuaternario";
import TituloQuinario from "./TituloQuinario";
import TituloSextario from "./TituloSextario";
import TituloSeptenario from "./TituloSeptenario";

export { AccionCuaternaria, AccionPrimaria, AccionQuinaria, AccionSecundaria, AccionTerciaria, BotonCuaternario, BotonPrimario, BotonSecundario, BotonTerciario, EnlaceAlternativoPrimario, EnlaceAlternativoSecundario, EnlaceCuaternario, EnlacePrimario, EnlaceSecundario, EnlaceTerciario, EntradaCampo, EntradaNumero, EntradaRadioPrimaria, EntradaRadioSecundaria, EntradaSeleccion, EntradaTexto, EntradaVerificacionPrimaria, EntradaVerificacionSecundaria, EtiquetaPrimaria, EtiquetaSecundaria, EtiquetaTerciaria, ListaPrimaria, ParrafoCuaternario, ParrafoPrimario, ParrafoSecundario, ParrafoTerciario, TituloPrimario, TituloSecundario, TituloTerciario, TituloCuaternario, TituloQuinario, TituloSextario, TituloSeptenario, };

const Elementos = { AccionCuaternaria, AccionPrimaria, AccionQuinaria, AccionSecundaria, AccionTerciaria, BotonCuaternario, BotonPrimario, BotonSecundario, BotonTerciario, EnlaceAlternativoPrimario, EnlaceAlternativoSecundario, EnlaceCuaternario, EnlacePrimario, EnlaceSecundario, EnlaceTerciario, EntradaCampo, EntradaNumero, EntradaRadioPrimaria, EntradaRadioSecundaria, EntradaSeleccion, EntradaTexto, EntradaVerificacionPrimaria, EntradaVerificacionSecundaria, EtiquetaPrimaria, EtiquetaSecundaria, EtiquetaTerciaria, ListaPrimaria, ParrafoCuaternario, ParrafoPrimario, ParrafoSecundario, ParrafoTerciario, TituloPrimario, TituloSecundario, TituloTerciario, TituloCuaternario, TituloQuinario, TituloSextario, TituloSeptenario, };

export default Elementos;